#ifndef POSTPROCESS_HLSL
#define POSTPROCESS_HLSL

#include "definitions.hpp"

FAZE_BEGIN_LAYOUT(Postprocess)

FAZE_BEGIN_DESCRIPTOR_LAYOUT
FAZE_TEXTURES(2)
FAZE_RWTEXTURES(1)
FAZE_END_DESCRIPTOR_LAYOUT

FAZE_CBUFFER
{
	int lol;
};

FAZE_SRV(Texture2D<float4>, source, 0)
FAZE_SRV(Texture2D<float4>, luminance, 1)
FAZE_UAV(RWTexture2D<float4>, output, 0)

FAZE_END_LAYOUT

#endif /*FAZE_SHADER_DEFINITIONS*/